### ISSUE TITLE
Shell/Ink problem

### ISSUE THREAD

**Issue by Fulji** [pie3636/fire-watcher#29]
"Open a shell and you might find some ink inside. Ink chance : 20 % to produce 3 ink. "  pourtant en ouvrant les shell 1 par 1 le max que je peux avoir c'est : "[21:43:00.990] You found 1 ink sac."

**Comment by pie3636** [comment]
Fixed in 0.7.7
(J'avais vraiment fait n'importe quoi... J'avais recopié un bout de fonction en l'adaptant rapidement, sauf que j'avais pas assez changé de choses, du coup ça t'aurait donné les 3 inks si et seulement si tu utilisais le Buy all, avec strictement plus de 100 shells, et que tu cliquais sur un numéro de tick divisible par 20 (autrement dit moins de 50 ms après pile le début d'une seconde). Donc évidemment tu risquais pas de tomber dessus xD
